const data = {
  torso: [
    {
      model: "MP_SBT_CT_Body",
      img: "Subterra_Torso_CR_thumb",
    },
    "Subterra_Torso_GR_thumb",
    "Subterra_Torso_HZ_thumb",
    "Subterra_Torso_JG_thumb",
    "Subterra_Torso_NV_thumb",
    "Subterra_Torso_PL_thumb",
    "Hydra_Torso_CR_thumb",
    "Hydra_Torso_DB_thumb",
    "Hydra_Torso_EM_thumb",
    "Hydra_Torso_JG_thumb",
    "Hydra_Torso_NV_thumb",
    "Hydra_Torso_PL_thumb",
    "Recon_Torso_CR_thumb",
    "Recon_Torso_DG_thumb",
    "Recon_Torso_JG_thumb",
    "Recon_Torso_MR_thumb",
    "Recon_Torso_NV_thumb",
    "Recon_Torso_PL_thumb",
    "Defender_Torso_CM_thumb",
    "Defender_Torso_CR_thumb",
    "Defender_Torso_JG_thumb",
    "Defender_Torso_NV_thumb",
    "Defender_Torso_OB_thumb",
    "Defender_Torso_PL_thumb",
    "Reactor_Torso_CR_thumb",
    "Reactor_Torso_JG_thumb",
    "Reactor_Torso_NV_thumb",
    "Reactor_Torso_PL_thumb",
    "Reactor_Torso_PR_thumb",
    "Reactor_Torso_PU_thumb",
  ],
  leftarm: [
    "Subterra_Left Arm_CR_thumb",
    "Subterra_Left Arm_GR_thumb",
    "Subterra_Left Arm_HZ_thumb",
    "Subterra_Left Arm_JG_thumb",
    "Subterra_Left Arm_NV_thumb",
    "Subterra_Left Arm_PL_thumb",
    "Hydra_Left Arm_CR_thumb",
    "Hydra_Left Arm_DB_thumb",
    "Hydra_Left Arm_EM_thumb",
    "Hydra_Left Arm_JG_thumb",
    "Hydra_Left Arm_NV_thumb",
    "Hydra_Left Arm_PL_thumb",
    "Recon_Left Arm_CR_thumb",
    "Recon_Left Arm_DG_thumb",
    "Recon_Left Arm_JG_thumb",
    "Recon_Left Arm_MR_thumb",
    "Recon_Left Arm_NV_thumb",
    "Recon_Left Arm_PL_thumb",
    "Defender_Left Arm_CM_thumb",
    "Defender_Left Arm_CR_thumb",
    "Defender_Left Arm_JG_thumb",
    "Defender_Left Arm_NV_thumb",
    "Defender_Left Arm_OB_thumb",
    "Defender_Left Arm_PL_thumb",
    "Reactor_Left Arm_CR_thumb",
    "Reactor_Left Arm_JG_thumb",
    "Reactor_Left Arm_NV_thumb",
    "Reactor_Left Arm_PL_thumb",
    "Reactor_Left Arm_PR_thumb",
    "Reactor_Left Arm_PU_thumb",
  ],
  rightarm: [
    "Subterra_Right Arm_CR_thumb",
    "Subterra_Right Arm_GR_thumb",
    "Subterra_Right Arm_HZ_thumb",
    "Subterra_Right Arm_JG_thumb",
    "Subterra_Right Arm_NV_thumb",
    "Subterra_Right Arm_PL_thumb",
    "Hydra_Right Arm_CR_thumb",
    "Hydra_Right Arm_DB_thumb",
    "Hydra_Right Arm_EM_thumb",
    "Hydra_Right Arm_JG_thumb",
    "Hydra_Right Arm_NV_thumb",
    "Hydra_Right Arm_PL_thumb",
    "Recon_Right Arm_CR_thumb",
    "Recon_Right Arm_DG_thumb",
    "Recon_Right Arm_JG_thumb",
    "Recon_Right Arm_MR_thumb",
    "Recon_Right Arm_NV_thumb",
    "Recon_Right Arm_PL_thumb",
    "Defender_Right Arm_CM_thumb",
    "Defender_Right Arm_CR_thumb",
    "Defender_Right Arm_JG_thumb",
    "Defender_Right Arm_NV_thumb",
    "Defender_Right Arm_OB_thumb",
    "Defender_Right Arm_PL_thumb",
    "Reactor_Right Arm_CR_thumb",
    "Reactor_Right Arm_JG_thumb",
    "Reactor_Right Arm_NV_thumb",
    "Reactor_Right Arm_PL_thumb",
    "Reactor_Right Arm_PR_thumb",
    "Reactor_Right Arm_PU_thumb",
  ],
  backpack: [
    "Subterra_Back Pack_CR_thumb",
    "Subterra_Back Pack_GR_thumb",
    "Subterra_Back Pack_HZ_thumb",
    "Subterra_Back Pack_JG_thumb",
    "Subterra_Back Pack_NV_thumb",
    "Subterra_Back Pack_PL_thumb",
    "Hydra_Back Pack_CR_thumb",
    "Hydra_Back Pack_DB_thumb",
    "Hydra_Back Pack_EM_thumb",
    "Hydra_Back Pack_JG_thumb",
    "Hydra_Back Pack_NV_thumb",
    "Hydra_Back Pack_PL_thumb",
    "Recon_Back Pack_CR_thumb",
    "Recon_Back Pack_DG_thumb",
    "Recon_Back Pack_JG_thumb",
    "Recon_Back Pack_MR_thumb",
    "Recon_Back Pack_NV_thumb",
    "Recon_Back Pack_PL_thumb",
    "Defender_Back Pack_CM_thumb",
    "Defender_Back Pack_CR_thumb",
    "Defender_Back Pack_JG_thumb",
    "Defender_Back Pack_NV_thumb",
    "Defender_Back Pack_OB_thumb",
    "Defender_Back Pack_PL_thumb",
    "Reactor_Back Pack_CR_thumb",
    "Reactor_Back Pack_JG_thumb",
    "Reactor_Back Pack_NV_thumb",
    "Reactor_Back Pack_PL_thumb",
    "Reactor_Back Pack_PR_thumb",
    "Reactor_Back Pack_PU_thumb",
  ],
  legs: [
    "Subterra_Legs_CR_thumb",
    "Subterra_Legs_GR_thumb",
    "Subterra_Legs_HZ_thumb",
    "Subterra_Legs_JG_thumb",
    "Subterra_Legs_NV_thumb",
    "Subterra_Legs_PL_thumb",
    "Hydra_Legs_CR_thumb",
    "Hydra_Legs_DB_thumb",
    "Hydra_Legs_EM_thumb",
    "Hydra_Legs_JG_thumb",
    "Hydra_Legs_NV_thumb",
    "Hydra_Legs_PL_thumb",
    "Recon_Legs_CR_thumb",
    "Recon_Legs_DG_thumb",
    "Recon_Legs_JG_thumb",
    "Recon_Legs_MR_thumb",
    "Recon_Legs_NV_thumb",
    "Recon_Legs_PL_thumb",
    "Defender_Legs_CM_thumb",
    "Defender_Legs_CR_thumb",
    "Defender_Legs_JG_thumb",
    "Defender_Legs_NV_thumb",
    "Defender_Legs_OB_thumb",
    "Defender_Legs_PL_thumb",
    "Reactor_Legs_CR_thumb",
    "Reactor_Legs_JG_thumb",
    "Reactor_Legs_NV_thumb",
    "Reactor_Legs_PL_thumb",
    "Reactor_Legs_PR_thumb",
    "Reactor_Legs_PU_thumb",
  ],
};

module.exports = data;
