export const data = [
    {
        name: 'Alfonso',
        searchText: 'Alfonso',
        supply: 50,
        generation: 1,
        properties: {
            speed: 10,
            weight: 100,
            bravery: 90,
            cunning: 80,
            special: 'gold',
            accessory: 'crown',
            eyeColor: 'gold',
            'robotic%': 0,
            baseColor: 'gold',
            traitCount: 11,
            intelligence: 50,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 10:58:37.000'
    },
    {
        name: 'Astro',
        searchText: 'Astro',
        supply: 100,
        generation: 1,
        properties: {
            speed: 30,
            weight: 60,
            bravery: 90,
            cunning: 60,
            special: 'astronaut',
            accessory: 'space suit',
            eyeColor: 'orange',
            'robotic%': 0,
            baseColor: 'gray',
            traitCount: 11,
            intelligence: 90,
        },
        mechCompatible: false,
        eventType: 'airdropped',
        mintDate: '2022-06-09 08:46:19.000'
    },
    {
        name: 'Cyber',
        searchText: 'Cyber',
        generation: 1,
        supply: 450,
        properties: {
            speed: 60,
            weight: 70,
            bravery: 70,
            cunning: 80,
            special: '50/50',
            accessory: 'spring legs',
            eyeColor: 'purple',
            'robotic%': 50,
            baseColor: 'green',
            traitCount: 11,
            intelligence: 80,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 10:41:15.000'
    },
    {
        name: 'Lucia',
        searchText: 'Lucia',
        supply: 100,
        generation: 1,
        properties: {
            speed: 80,
            weight: 60,
            bravery: 80,
            cunning: 60,
            special: 'rage',
            accessory: 'horns',
            eyeColor: 'red',
            'robotic%': 0,
            baseColor: 'red',
            traitCount: 11,
            intelligence: 70,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 09:38:11.000'
    },
    {
        name: 'Max',
        searchText: 'Max',
        generation: 1,
        supply: 850,
        properties: {
            speed: 50,
            weight: 50,
            bravery: 30,
            cunning: 50,
            special: 'none',
            accessory: '3d glasses',
            eyeColor: 'blue',
            'robotic%': 0,
            baseColor: 'pink',
            traitCount: 10,
            intelligence: 40,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 12:39:16.000'
    },
    {
        name: 'Mittens',
        searchText: 'Mittens',
        generation: 1,
        supply: 800,
        properties: {
            speed: 30,
            weight: 20,
            bravery: 60,
            cunning: 10,
            special: 'none',
            accessory: 'buttons',
            eyeColor: 'brown',
            'robotic%': 0,
            baseColor: 'green',
            traitCount: 10,
            intelligence: 20,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 13:50:02.000'
    },
    {
        name: 'Mucca',
        searchText: 'Mucca',
        generation: 1,
        supply: 650,
        properties: {
            speed: 20,
            weight: 60,
            bravery: 20,
            cunning: 10,
            special: 'none',
            accessory: 'none',
            eyeColor: 'blue',
            'robotic%': 0,
            baseColor: 'blue',
            traitCount: 9,
            intelligence: 20,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 16:52:36.000'
    },
    {
        name: 'PavBot',
        searchText: 'Bot',
        generation: 1,
        supply: 150,
        properties: {
            speed: 100,
            weight: 80,
            bravery: 90,
            cunning: 80,
            special: 'tron lines',
            accessory: 'super eyes',
            eyeColor: 'red',
            'robotic%': 100,
            baseColor: 'orange',
            traitCount: 11,
            intelligence: 90,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 09:50:26.000'
    },
    {
        name: 'PavyJones',
        searchText: 'Pavy',
        generation: 1,
        supply: 500,
        properties: {
            speed: 80,
            weight: 0,
            bravery: 80,
            cunning: 90,
            special: 'transparency',
            accessory: 'priate costume',
            eyeColor: 'black',
            'robotic%': 0,
            baseColor: 'green',
            traitCount: 11,
            intelligence: 100,
        },
        mechCompatible: false,
        eventType: 'airdropped',
        mintDate: '2022-05-13 11:52:46.000'
    },
    {
        name: 'Rex',
        searchText: 'Rex',
        generation: 1,
        supply: 700,
        properties: {
            speed: 80,
            weight: 50,
            bravery: 60,
            cunning: 20,
            special: 'vision',
            accessory: 'none',
            eyeColor: 'blue',
            'robotic%': 0,
            baseColor: 'blue',
            traitCount: 10,
            intelligence: 10,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 17:38:36.000'
    },
    {
        name: 'Shell',
        searchText: 'Shell',
        generation: 1,
        supply: 400,
        properties: {
            speed: 30,
            weight: 30,
            bravery: 10,
            cunning: 10,
            special: 'none',
            accessory: 'egg shell',
            eyeColor: 'blue',
            'robotic%': 0,
            baseColor: 'green',
            traitCount: 10,
            intelligence: 100,
        },
        mechCompatible: false,
        eventType: 'airdropped',
        mintDate: '2022-05-13 11:24:30.000'
    },
    {
        name: 'Sky',
        searchText: 'Sky',
        generation: 1,
        supply: 600,
        properties: {
            speed: 40,
            weight: 50,
            bravery: 30,
            cunning: 40,
            special: 'none',
            accessory: 'box',
            eyeColor: 'pruple',
            'robotic%': 10,
            baseColor: 'purple',
            traitCount: 10,
            intelligence: 50,
        },
        mechCompatible: false,
        eventType: 'airdropped',
        mintDate: '2022-05-13 16:22:33.000'
    },
    {
        name: 'Sparkles',
        searchText: 'Sparkles',
        generation: 1,
        supply: 750,
        properties: {
            speed: 60,
            weight: 50,
            bravery: 60,
            cunning: 60,
            special: 'magic',
            accessory: 'none',
            eyeColor: 'pruple',
            'robotic%': 0,
            baseColor: 'rainbow',
            traitCount: 10,
            intelligence: 60,
        },
        mechCompatible: true,
        eventType: 'airdropped',
        mintDate: '2022-05-13 15:31:17.000'
    },
    {
        name: 'Jones',
        searchText: 'Jones',
        supply: 50,
        generation: 2,
        properties: {
            speed: 50,
            weight: 50,
            bravery: 70,
            cunning: 70,
            special: 'adventure',
            accessory: 'whip',
            eyeColor: 'brown',
            'robotic%': 0,
            baseColor: 'teal',
            traitCount: 11,
            intelligence: 40,
        },
        mechCompatible: true,
        eventType: 'specialEvent',
        mintDate: '2022-09-14 10:33:35.000'
    },
    {
        name: 'London',
        searchText: 'London',
        generation: 2,
        supply: 250,
        properties: {
            speed: 40,
            weight: 20,
            bravery: 60,
            cunning: 50,
            special: 'union jack',
            accessory: 'none',
            eyeColor: 'red',
            'robotic%': 0,
            baseColor: 'blue',
            traitCount: 10,
            intelligence: 60,
        },
        mechCompatible: true,
        eventType: 'specialEvent',
        mintDate: '2022-11-02 19:17:11.000'
    },
    {
        name: 'Akira',
        searchText: 'Akira',
        generation: 2,
        supply: 644,
        properties: {
            speed: 60,
            weight: 50,
            bravery: 50,
            cunning: 30,
            special: 'wild',
            accessory: 'none',
            eyeColor: 'washed out red',
            'robotic%': 60,
            baseColor: 'light purple',
            traitCount: 10,
            intelligence: 50,
        },
        mechCompatible: true,
        eventType: 'cyberLiveEvent',
        mintDate: '2022-12-18 08:18:05.000'
    },
    {
        name: 'Alpha',
        searchText: 'Alpha',
        generation: 2,
        supply: 628,
        properties: {
            speed: 50,
            weight: 60,
            bravery: 60,
            cunning: 20,
            special: 'wild',
            accessory: 'none',
            eyeColor: 'yellow',
            'robotic%': 50,
            baseColor: 'purple',
            traitCount: 10,
            intelligence: 40,
        },
        mechCompatible: true,
        eventType: 'cyberLiveEvent',
        mintDate: '2022-12-19 10:46:24.000'
    },
    {
        name: 'App',
        searchText: 'App',
        generation: 2,
        supply: 648,
        properties: {
            speed: 50,
            weight: 40,
            bravery: 50,
            cunning: 30,
            special: 'wild',
            accessory: 'none',
            eyeColor: 'cyan',
            'robotic%': 30,
            baseColor: 'orange',
            traitCount: 10,
            intelligence: 30,
        },
        mechCompatible: true,
        eventType: 'cyberLiveEvent',
        mintDate: '2022-12-19 13:54:56.000'
    },
    {
        name: 'Arin',
        searchText: 'Arin',
        generation: 2,
        supply: 636,
        properties: {
            speed: 60,
            weight: 60,
            bravery: 50,
            cunning: 30,
            special: 'wild',
            accessory: 'none',
            eyeColor: 'red',
            'robotic%': 60,
            baseColor: 'grey',
            traitCount: 10,
            intelligence: 50,
        },
        mechCompatible: true,
        eventType: 'cyberLiveEvent',
        mintDate: '2022-12-20 08:38:40.000'
    },
    {
        name: 'Auto',
        searchText: 'Auto',
        generation: 2,
        supply: 617,
        properties: {
            speed: 30,
            weight: 30,
            bravery: 40,
            cunning: 40,
            special: 'wild',
            accessory: 'none',
            eyeColor: 'orange',
            'robotic%': 30,
            baseColor: 'cyan',
            traitCount: 10,
            intelligence: 30,
        },
        mechCompatible: true,
        eventType: 'cyberLiveEvent',
        mintDate: '2022-12-20 01:40:11.000'
    },
    {
        name: 'Axis',
        searchText: 'Axis',
        generation: 2,
        supply: 652,
        properties: {
            speed: 50,
            weight: 60,
            bravery: 60,
            cunning: 20,
            special: 'wild',
            accessory: 'none',
            eyeColor: 'blue',
            'robotic%': 50,
            baseColor: 'green',
            traitCount: 10,
            intelligence: 40,
        },
        mechCompatible: true,
        eventType: 'cyberLiveEvent',
        mintDate: '2022-12-18 10:16:41.000'
    }
]